import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion, useScroll, useTransform, useReducedMotion} from 'framer-motion';
import {ArrowDown, ArrowUpRight, Github, Linkedin, Mail, Menu, X, Download, BarChart3, Database, FileSpreadsheet, Code2, Brain, ExternalLink} from 'lucide-react';
import './styles.css';

const projects = [
 {n:'01',type:'ACADEMIC PROJECT',title:'Impact of Social Media Usage on Academic Performance of College Students',desc:'A questionnaire-based statistical study exploring the relationship between social media usage and the academic performance of college students.',tools:['Statistics','Excel','Data Analysis']},
 {n:'02',type:'DATA ANALYTICS',title:'Customer Delinquency & Missed Payment Analysis',desc:'Analyzed customer financial data to understand missed-payment patterns, identify important customer segments and translate predictive insights into practical collection recommendations.',tools:['Python','Data Analysis','Statistics','Excel']},
 {n:'03',type:'TABLEAU',title:'Daikibo Telemetry Analysis',desc:'Analyzed industrial telemetry data using Tableau to explore machine activity, operational patterns and performance across facilities.',tools:['Tableau','Data Visualization','Data Analysis']},
 {n:'04',type:'PYTHON',title:'Python Data Analytics Practice',desc:'A collection of practical Python exercises created while developing programming and data-analysis fundamentals.',tools:['Python','Problem Solving','Data Handling']}
];
const skills=[['DATA ANALYTICS',['Data Analysis','Data Cleaning','Data Interpretation','Statistical Analysis','Data Visualization','Business Analysis']],['PROGRAMMING',['Python','SQL','C++']],['TOOLS',['Microsoft Excel','Google Sheets','Tableau','AI Tools','Prompting']],['CORE SKILLS',['Analytical Thinking','Problem Solving','Communication','Teamwork','Time Management','Adaptability']]];
const certs=['Business Analysis & Process Management — Coursera','Introduction to Data Analysis using Microsoft Excel — Coursera','Understanding Basic SQL Syntax — Coursera','Google AI Essentials — Google','Introduction to Data Engineering — IBM'];
const tech=['Python','SQL','Excel','Statistics','Tableau','Google Sheets','Business Analysis','AI Tools'];

function Fade({children,delay=0,className='' }:{children:React.ReactNode,delay?:number,className?:string}){const reduce=useReducedMotion();return <motion.div className={className} initial={{opacity:0,y:reduce?0:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'50px',amount:0.15}} transition={{duration:.7,delay,ease:[.25,.1,.25,1]}}>{children}</motion.div>}
function Button({children,href='#contact',primary=false}:{children:React.ReactNode,href?:string,primary?:boolean}){return <motion.a whileHover={{y:-3,scale:1.02}} whileTap={{scale:.98}} href={href} className={primary?'btn btn-primary':'btn btn-ghost'}>{children}</motion.a>}
function Nav(){const [open,setOpen]=useState(false);const links=['about','skills','projects','education','certifications','contact'];return <header className="nav-wrap"><nav className="nav"><a className="brand" href="#home">ADHISH B<span>.</span></a><div className="desktop-links">{links.map(x=><a key={x} href={'#'+x}>{x}</a>)}</div><div className="social-nav"><a aria-label="LinkedIn" href="https://www.linkedin.com/in/adhish-b-a42a35412/" target="_blank"><Linkedin size={19}/></a><a aria-label="GitHub" href="https://github.com/adhish744-arch" target="_blank"><Github size={19}/></a><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="menu">{open?<X/>:<Menu/>}</button></div></nav>{open&&<div className="mobile-menu">{links.map(x=><a onClick={()=>setOpen(false)} key={x} href={'#'+x}>{x}</a>)}</div>}</header>}
function Hero(){return <section id="home" className="hero"><div className="hero-grid"/><Nav/><div className="hero-content"><Fade><div className="eyebrow"><span/> DATA ANALYTICS • PYTHON • STATISTICS</div><h1>Hi, I’m <em>Adhish</em></h1><p className="hero-copy">Turning data into meaningful insights through statistics, analytics and technology.</p><div className="hero-actions"><Button primary href="#projects">View My Projects <ArrowDown size={17}/></Button><Button href="#contact">Let’s Connect <ArrowUpRight size={17}/></Button></div></Fade><motion.div className="portrait-shell" initial={{opacity:0,scale:.92,y:30}} animate={{opacity:1,scale:1,y:0}} transition={{duration:.9,delay:.35,ease:[.25,.1,.25,1]}}><div className="portrait-ring"><img src="/assets/adhish.jpg" alt="Adhish B portrait"/></div><span className="float-tag tag1">Python</span><span className="float-tag tag2">SQL</span><span className="float-tag tag3">Excel</span><span className="float-tag tag4">Statistics</span></motion.div></div><div className="hero-bottom"><span>LEARN • ANALYZE • BUILD • GROW</span><a href="#about"><ArrowDown/></a></div></section>}
function Marquee(){return <section className="marquee"><div className="marquee-track">{[...tech,...tech].map((t,i)=><span key={i}>{t}<b>✦</b></span>)}</div></section>}
function About(){return <section id="about" className="section about"><Fade><p className="section-kicker">01 / ABOUT</p><h2>About <span>me</span></h2></Fade><div className="about-grid"><Fade delay={.1}><div><p className="lead">I’m a BSc Statistics student with a growing interest in <strong>Data Analytics, Business Analytics and IT.</strong></p><p>I enjoy working with data, learning Python and SQL, and transforming information into meaningful insights. My academic background in Statistics gives me a strong foundation in analytical and quantitative thinking, while my growing technical skills help me approach real-world data problems with curiosity and a practical mindset.</p></div></Fade><div className="stat-grid">{[['BSc','Statistics'],['5+','Technical Areas'],['5+','Certifications'],['4+','Projects']].map(([a,b],i)=><Fade delay={.12+i*.08} key={b}><div className="stat"><strong>{a}</strong><span>{b}</span></div></Fade>)}</div></div></section>}
function Skills(){return <section id="skills" className="section skills"><Fade><p className="section-kicker">02 / SKILLS</p><h2>What I <span>work with</span></h2></Fade><div className="skill-grid">{skills.map(([title,items],i)=><Fade key={title} delay={i*.08}><div className="skill-card"><div className="skill-head"><span>0{i+1}</span><h3>{title}</h3></div><div className="pills">{(items as string[]).map(x=><span key={x}>{x}</span>)}</div></div></Fade>)}</div></section>}
function Projects(){return <section id="projects" className="section projects"><Fade><p className="section-kicker">03 / SELECTED WORK</p><h2>Featured <span>projects</span></h2></Fade><div className="project-stack">{projects.map((p,i)=><ProjectCard key={p.n} p={p} i={i}/>)}</div></section>}
function ProjectCard({p,i}:{p:typeof projects[number],i:number}){const ref=React.useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','start start']});const scale=useTransform(scrollYProgress,[0,1],[1,1-i*.025]);return <motion.article ref={ref} style={{scale,top:i*18}} className="project-card"><div className="project-top"><div className="project-no">{p.n}</div><div><p className="project-type">{p.type}</p><h3>{p.title}</h3></div><a className="live" href="#contact">View Project <ArrowUpRight size={17}/></a></div><div className="project-body"><div className="project-info"><p>{p.desc}</p><div className="project-tools">{p.tools.map(t=><span key={t}>{t}</span>)}</div></div><div className="project-visual"><BarChart3/><span>PROJECT<br/>INSIGHT</span></div></div></motion.article>}
function Education(){return <section id="education" className="section light"><Fade><p className="section-kicker dark">04 / EDUCATION</p><h2>Academic <span>journey</span></h2></Fade><div className="timeline"><Fade><div className="timeline-item"><span>2023 — 2026</span><div><h3>BSc Statistics</h3><p>Kannur University · Govinda Pai Memorial Government College Manjeshwar</p><small>Pursuing / Pending completion</small></div></div></Fade><Fade delay={.1}><div className="timeline-item"><span>2021 — 2023</span><div><h3>Higher Secondary — Computer Science</h3><p>CJHSS Chemanad</p></div></div></Fade><Fade delay={.2}><div className="timeline-item"><span>2021</span><div><h3>SSLC</h3><p>CJHSS Chemanad</p></div></div></Fade></div></section>}
function Certifications(){return <section id="certifications" className="section certs"><Fade><p className="section-kicker">05 / CERTIFICATIONS</p><h2>Courses & <span>certificates</span></h2></Fade><div className="cert-list">{certs.map((c,i)=><Fade key={c} delay={i*.06}><div className="cert"><span>0{i+1}</span><p>{c}</p><ArrowUpRight size={20}/></div></Fade>)}</div></section>}
function Beyond(){return <section className="section beyond"><div className="beyond-grid"><Fade><div className="mini-card"><Brain/><p>BEYOND ACADEMICS</p><h3>NCC Cadet</h3><span>Participated during school years from 8th to 10th Standard.</span></div></Fade><Fade delay={.1}><div className="mini-card"><BarChart3/><p>COMMUNITY</p><h3>NSS Participant</h3><span>Participated in campus and community activities.</span></div></Fade><Fade delay={.2}><div className="mini-card"><Code2/><p>LANGUAGES</p><h3>English · Malayalam · Kannada</h3><span>Communication across three languages.</span></div></Fade></div></section>}
function Contact(){return <section id="contact" className="contact"><div className="contact-grid"/><Fade><p className="section-kicker">06 / CONTACT</p><h2>Let’s build something <span>with data.</span></h2><p className="contact-copy">I’m open to learning opportunities, internships, entry-level roles, collaborative projects and meaningful conversations around data and technology.</p><div className="contact-actions"><Button primary href="mailto:adhish744@gmail.com"><Mail size={18}/> Email Me</Button><Button href="https://www.linkedin.com/in/adhish-b-a42a35412/">LinkedIn <Linkedin size={18}/></Button><Button href="https://github.com/adhish744-arch">GitHub <Github size={18}/></Button></div></Fade><footer><span>ADHISH B.</span><small>© 2026 Adhish B. All rights reserved.</small><a href="#home">Back to top <ArrowUpRight size={15}/></a></footer></section>}
function App(){useEffect(()=>{document.documentElement.style.scrollBehavior='smooth';return()=>{document.documentElement.style.scrollBehavior='auto'}},[]);return <main><Hero/><Marquee/><About/><Skills/><Projects/><Education/><Certifications/><Beyond/><Contact/></main>}

createRoot(document.getElementById('root')!).render(<App/>);
